name: Example 00
on: 
    [workflow_dispatch]
jobs:
    Explore-options:
        runs-on: ubuntu-latest
        steps:
            - name: first step
              run: |
                echo "Hello"
