name: example 01
on: [workflow_dispatch]
jobs:
  explore-github-actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ github.event_name }}"
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{github}}"
